
services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: libreria_riw
      MYSQL_ROOT_PASSWORD: 333
      MYSQL_USER: libreria_user
      MYSQL_PASSWORD: 333
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
