version: '3.8'

services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 401178
      MYSQL_DATABASE: Librería_RIW
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
